#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use Factory\Application;
use Factory\Console\Make\ClassCommand;
use Factory\Console\Make\InterfaceCommand;
use Factory\Console\Make\TraitCommand;
use Factory\Console\Make\TestCommand;
use Symfony\Component\Console\Output\ConsoleOutput;


try
{
    /*
     * Setup the application
     */
    $app = new Application('1.0.0');
    $app->container->bind(Filesystem::class, function() {
        return new Filesystem(new Local(getcwd()));
    });

    /*
     * Register Commands
     */
    $app->add($app->container->make(ClassCommand::class));
    $app->add($app->container->make(InterfaceCommand::class));
    $app->add($app->container->make(TraitCommand::class));
    $app->add($app->container->make(TestCommand::class));

    /*
     * Run the application
     */
    $app->run();

}
catch(Exception $e)
{
    $output = new ConsoleOutput;
    $output->writeln("<error>{$e->getMessage()}</error>");
}

